version: "3.7"
networks:
  frontend:
    labels:
      network.description: "Front end network"
  backend:
    labels:
      network.description: "Network for backend services"
  db:
    labels:
      network.description: "Network for database services"

services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - frontend
      - backend

  backend:
    image: michal/szturc/cambrige-recruitment-backend:latest
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: docker, flyway
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
      DB_POSTGRES_NAME: ${DB_NAME}
      DB_POSTGRES_USER: ${DB_USER}
      DB_POSTGRES_PASS: ${DB_PASS}
      DB_POSTGRES_HOST: ${DB_HOST}
    ports:
      - "8081:8080"
      - "5005:5005"
    networks:
      - db
      - backend
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:12
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /databases/${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - db
    volumes:
      - ./db-data:/databases/app-db